/**
 * Centralized UI copy (spec §1.3 + §4: "Dejá los textos centralizados en un
 * solo módulo para poder traducir después"). English, matching the design.
 *
 * VOCABULARY RULES (§1.3) — enforced here so the rest of the app can't drift:
 *   USE:   Ready, Review required, Missing, Not requested, Pending, In review
 *   NEVER: Compliant, Certified, Safe, "Approved by Elaris"
 *   USE:   "Approved by <name>, <role>, <date>"
 *   USE:   Evidence coverage (never "Compliance %")
 *   USE:   Readiness (never "Compliance score" / "risk score")
 */

export const copy = {
  brand: {
    name: "Elaris",
    subtitle: "Deployment & Change Evidence",
  },
  nav: {
    home: "Home",
    robots: "Robots",
    deployments: "Deployments",
    evidence: "Evidence",
    requirements: "Requirements",
    changes: "Changes",
    incidents: "Incidents",
    reports: "Reports",
    assistant: "Assistant",
    assistantComingSoon: "Coming soon",
  },
  topbar: {
    searchPlaceholder: "Search robots, deployments, evidence…",
    organization: "Humandroid",
    viewingAs: "Viewing as",
    attentionRequired: "Attention Required",
  },
  demoBanner: "Demo data",
  reportFooter:
    "Generated by Elaris on {date}. Elaris does not certify or approve; approvals are recorded by the named persons.",
  home: {
    title: "Home",
    kpis: {
      activeDeployments: "Active Deployments",
      robots: "Robots",
      openGaps: "Open Gaps",
      reviewRequired: "Review Required",
    },
    vsLast30: "vs last 30 days",
    attentionRequired: "Attention Required",
    activeDeployments: "Active Deployments",
    recentChanges: "Recent Changes",
    missingEvidence: "Missing Evidence",
    upcomingReviews: "Upcoming Reviews",
    incidents: "Incidents",
    readiness: "Readiness",
    viewAll: "View all",
  },
  common: {
    edit: "Edit",
    viewAll: "View all",
    viewDetails: "View details",
    owner: "Owner",
    status: "Status",
    item: "Item",
    relatedTo: "Related To",
    type: "Type",
    date: "Date",
    dueDate: "Due Date",
    asset: "Asset",
    change: "Change",
    author: "Author",
    impact: "Impact",
    reason: "Reason",
    category: "Category",
    suggestedAction: "Suggested Action",
    description: "Description",
    severity: "Severity",
    role: "Role",
    person: "Person",
    approval: "Approval",
  },
  approvedBy: (name: string, role: string, date: string) => `Approved by ${name}, ${role}, ${date}`,
  coverage: {
    label: "Evidence coverage",
    linked: (linked: number, applicable: number) => `${linked} of ${applicable} applicable evidence items linked`,
  },
} as const;

export type Copy = typeof copy;
